name: File Size

on:
  pull_request:
  push:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  file-size:
    uses: dryvist/.github/.github/workflows/_file-size.yml@c4501ea67ce4469a5cc95216c9a989516da2adb8 # v1.10.0
