name: Markdown Lint

on:
  pull_request:
    paths: ["**/*.md"]
  push:
    branches: [main, develop]
    paths: ["**/*.md"]

permissions:
  contents: read

jobs:
  markdown-lint:
    uses: dryvist/.github/.github/workflows/_markdown-lint.yml@0aab1ddaecacea5dc9752b075e2ac10491af33bf # v1.11.3
