name: Markdown Lint

on:
  pull_request:
    paths: ["**/*.md"]
  push:
    branches: [main, develop]
    paths: ["**/*.md"]

permissions:
  contents: read

jobs:
  markdown-lint:
    uses: dryvist/.github/.github/workflows/_markdown-lint.yml@c4501ea67ce4469a5cc95216c9a989516da2adb8 # v1.10.0
